pub const EQUIVALENCE_RULES: &[(&str, &str, &str)] = &[
    ("comm-or", "(?a | ?b)", "(?b | ?a)"),
    ("assoc-and", "((?a & ?b) & ?c)", "(?a & (?b & ?c))"),
    ("comm-and", "(?a & ?b)", "(?b & ?a)"),
    ("and-zero", "(?a & 0)", "0"),
    ("inv-xor", "(?a ^ ?a)", "0"),
    ("comm-xor", "(?a ^ ?b)", "(?b ^ ?a)"),
    ("zero-or-rev", "(?a | 0)", "?a"),
    ("zero-xor-rev", "(?a ^ 0)", "?a"),
    ("inv-xor-rev", "0", "($r:int ^ $r:int)"),
    ("zero-or", "?a:int", "(?a | 0)"),
    ("zero-xor", "?a:int", "(?a ^ 0)"),
    ("idem-and", "?a:int", "(?a & ?a)"),
    ("zero-and", "0", "($r:int & 0)"),
    ("comm-add", "(?a + ?b)", "(?b + ?a)"),
    ("comm-mul", "(?a * ?b)", "(?b * ?a)"),
    ("comm-div", "(?a / ?b)", "((1 / ?b) * ?a)"),
    (
        "dist-mul-add",
        "((?a + ?b) * ?c)",
        "((?a * ?c) + (?b * ?c))",
    ),
    (
        "dist-add-mul",
        "((?a * ?c) + (?b * ?c))",
        "((?a + ?b) * ?c)",
    ),
    ("assoc-add", "((?a + ?b) + ?c)", "(?a + (?b + ?c))"),
    ("assoc-add-rev", "(?a + (?b + ?c))", "((?a + ?b) + ?c)"),
    ("assoc-mul", "((?a * ?b) * ?c)", "(?a * (?b * ?c))"),
    ("assoc-mul-rev", "(?a * (?b * ?c))", "((?a * ?b) * ?c)"),
    ("assoc-div", "((?a / ?b) * ?c)", "(?a * (?c / ?b))"),
    ("assoc-div-rev", "(?a * (?c / ?b))", "((?a / ?b) * ?c)"),
    ("zero-add-des", "(?a + 0)", "?a"),
    ("one-mul-des", "(?a * 1)", "?a"),
    ("one-div-des", "(?a / 1)", "?a"),
    ("inv-zero-add-des", "(?a - 0)", "?a"),
    ("neg-zero-add-des", "(0 - ?a)", "(-?a)"),
    ("inv-add-des", "(?a - ?a)", "0"),
    ("inv-assoc-neg2pos", "((?a - ?b) - ?c)", "(?a - (?b + ?c))"),
    ("inv-assoc-pos2neg", "(?a - (?b + ?c))", "((?a - ?b) - ?c)"),
    ("inv_addition_inl", "(?a + (-?c))", "(?a - ?c)"),
    ("double-negation-add-des", "(-(-?a))", "?a"),
    ("zero-add-con", "?a:int", "(?a + 0)"),
    ("one-mul-con", "?a:int", "(?a * 1)"),
    ("one-div-con", "?a:int", "(?a / 1)"),
    ("inv-zero-add-con", "?a:int", "(?a - 0)"),
    ("neg-zero-add-con", "(-?a)", "(0 - ?a)"),
    ("inv_addition_exp", "(?a - ?c)", "(?a + (-?c))"),
    ("double-negation-add-con", "?a:int", "(-(-?a))"),
    ("add_sub_random_value", "?a:int", "((?a - $r:int) + $r:int)"),
    ("inv-div-des", "(?a / ?a)", "1"),
    ("zero-bor-des", "(?a | F)", "?a"),
    ("zero-band-des", "(?a & T)", "?a"),
    ("taut-bor", "(?a | T)", "T"),
    ("contra-band", "(?a & F)", "F"),
    ("assoc-bor", "((?a | ?b) | ?c)", "(?a | (?b | ?c))"),
    ("assoc-band", "((?a & ?b) & ?c)", "(?a & (?b & ?c))"),
    ("comm-bor", "(?a | ?b)", "(?b | ?a)"),
    ("comm-ban", "(?a & ?b)", "(?b & ?a)"),
    (
        "dist-bor-band",
        "((?a & ?b) | ?c)",
        "((?a | ?c) & (?b | ?c))",
    ),
    (
        "dist-band-bor",
        "((?a | ?c) & (?b | ?c))",
        "((?a & ?b) | ?c)",
    ),
    ("de-morgan-band-con", "(!(?a & ?b))", "((!?a) | (!?b))"),
    ("de-morgan-band-des", "((!?a) | (!?b))", "(!(?a & ?b))"),
    ("de-morgan-bor-con", "(!(?a | ?b))", "((!?a) & (!?b))"),
    ("de-morgan-bor-des", "((!?a) & (!?b))", "(!(?a | ?b))"),
    ("double-negation-des", "(!(!?a))", "?a"),
    ("double-band-des", "(?a & ?a)", "?a:bool"),
    ("double-bor-des", "(?a | ?a)", "?a:bool"),
    ("zero-bor-con", "?a:bool", "(?a | F)"),
    ("zero-band-con", "?a:bool", "(?a & T)"),
    ("double-negation-con", "?a:bool", "(!(!?a))"),
    ("double-band-con", "?a:bool", "(?a & ?a)"),
    ("double-bor-con", "?a:bool", "(?a | ?a)"),
    ("commutativity-equ", "(?a == ?b)", "(?b == ?a)"),
    ("relation-geq-to-leq", "(?a >= ?b)", "(?b <= ?a)"),
    ("relation-leq-to-geq", "(?a <= ?b)", "(?b >= ?a)"),
    (
        "relation-leq-to-lth-and-equ",
        "(?a <= ?b)",
        "((?a < ?b) | (?a == ?b))",
    ),
    (
        "relation-lth-and-equ-to-leq",
        "((?a < ?b) | (?a == ?b))",
        "(?a <= ?b)",
    ),
    (
        "relation-geq-to-gth-and-equ",
        "(?a >= ?b)",
        "((?a > ?b) | (?a == ?b))",
    ),
    (
        "relation-gth-and-equ-to-geq",
        "((?a > ?b) | (?a == ?b))",
        "(?a >= ?b)",
    ),
    ("relation-leq-to-not-gth", "(?a <= ?b)", "(!(?a > ?b))"),
    ("relation-not-gth-to-leq", "(!(?a > ?b))", "(?a <= ?b)"),
    ("relation-geq-to-not-lth", "(?a >= ?b)", "(!(?a < ?b))"),
    ("relation-not-lth-to-geq", "(!(?a < ?b))", "(?a >= ?b)"),
    ("relation-neq-to-not-equ", "(?a != ?b)", "(!(?a == ?b))"),
    ("relation-not-equ-to-neq", "(!(?a == ?b))", "(?a != ?b)"),
    ("absorb-mul-zero", "(?a * 0)", "0"),
    ("absorb-zero-mul", "(0 * ?a)", "0"),
    ("expand-mul-zero", "0", "($r:int * 0)"),
    ("div-by-self-to-one", "(?a / ?a)", "1"),
    ("mod-by-self", "(?a % ?a)", "0"),
    ("zero-mod", "(0 % ?a)", "0"),
    (
        "expand-square-diff",
        "((?a - ?b) * (?a - ?b))",
        "(((?a * ?a) - (2 * (?a * ?b))) + (?b * ?b))",
    ),
    (
        "contract-square-diff",
        "(((?a * ?a) - (2 * (?a * ?b))) + (?b * ?b))",
        "((?a - ?b) * (?a - ?b))",
    ),
    (
        "expand-square-sum",
        "((?a + ?b) * (?a + ?b))",
        "(((?a * ?a) + (2 * (?a * ?b))) + (?b * ?b))",
    ),
    (
        "contract-square-sum",
        "(((?a * ?a) + (2 * (?a * ?b))) + (?b * ?b))",
        "((?a + ?b) * (?a + ?b))",
    ),
    ("neg-div-numerator", "((-?a) / ?b)", "(-(?a / ?b))"),
    ("neg-div-denominator", "(?a / (-?b))", "(-(?a / ?b))"),
    ("neg-div-unfactor-num", "(-(?a / ?b))", "((-?a) / ?b)"),
    ("neg-div-unfactor-den", "(-(?a / ?b))", "(?a / (-?b))"),
    ("sub-as-neg-add", "(?a - ?b)", "(?a + (0 - ?b))"),
    ("neg-add-as-sub", "(?a + (0 - ?b))", "(?a - ?b)"),
    (
        "mul-add-factor",
        "((?a * ?c) + (?a * ?d))",
        "(?a * (?c + ?d))",
    ),
    (
        "mul-sub-factor",
        "((?a * ?c) - (?a * ?d))",
        "(?a * (?c - ?d))",
    ),
    ("ternary-to-bool-mul", "(?cond ? ?a : 0)", "(?cond * ?a)"),
    ("bool-mul-to-ternary", "(?cond * ?a)", "(?cond ? ?a : 0)"),
    ("complement-to-xor", "(!?a)", "(?a ^ 1)"),
    ("xor-one-to-complement", "(?a ^ 1)", "(!?a)"),
    ("shift-left-zero", "(?a << 0)", "?a"),
    ("shift-right-zero", "(?a >> 0)", "?a"),
    ("add-inverse-random", "?a:int", "((?a + $r:int) - $r:int)"),
    ("mul-inverse-random", "?a:int", "((?a * $r:int) / $r:int)"),
    ("xor-inverse-random", "?a:int", "((?a ^ $r:int) ^ $r:int)"),
    ("and-or-identity", "((?a & ?b) | (?a & (!?b)))", "?a"),
    (
        "or-and-distribute",
        "(?a | (?b & ?c))",
        "((?a | ?b) & (?a | ?c))",
    ),
    (
        "and-or-distribute",
        "(?a & (?b | ?c))",
        "((?a & ?b) | (?a & ?c))",
    ),
    ("relation-lt-to-not-geq", "(?a < ?b)", "(!(?a >= ?b))"),
    ("relation-not-geq-to-lt", "(!(?a >= ?b))", "(?a < ?b)"),
    ("relation-gt-to-not-leq", "(?a > ?b)", "(!(?a <= ?b))"),
    ("relation-not-leq-to-gt", "(!(?a <= ?b))", "(?a > ?b)"),
    ("bool-and-to-mul", "(?a & ?b)", "((?a * ?b) != 0)"),
    ("bool-or-to-add", "(?a | ?b)", "((?a + ?b) != 0)"),
    (
        "mod-add-distribute",
        "((?a + ?b) % ?c)",
        "(((?a % ?c) + (?b % ?c)) % ?c)",
    ),
    (
        "mod-mul-distribute",
        "((?a * ?b) % ?c)",
        "(((?a % ?c) * (?b % ?c)) % ?c)",
    ),
    ("sub-same-term", "((?a + ?b) - ?a)", "?b"),
    ("sub-same-term-reverse", "((?a + ?b) - ?b)", "?a"),
    ("and-with-or-same", "((?a | ?b) & ?a)", "?a"),
    ("or-with-and-same", "((?a & ?b) | ?a)", "?a"),
    (
        "comparison-chain-trans",
        "((?a < ?b) & (?b < ?c))",
        "(?a < ?c)",
    ),
    ("negate-comparison-lt", "(!(?a < ?b))", "(?a >= ?b)"),
    ("negate-comparison-gt", "(!(?a > ?b))", "(?a <= ?b)"),
    ("mul-neg-one-to-neg", "(?a * (-1))", "(-?a)"),
    ("neg-to-mul-neg-one", "(-?a)", "(?a * (-1))"),
    ("div-neg-one-to-neg", "(?a / (-1))", "(-?a)"),
    ("add-self-to-mul-two", "(?a + ?a)", "(?a * 2)"),
    ("mul-two-to-add-self", "(?a * 2)", "(?a + ?a)"),
    ("bool-not-via-xor-one", "(!?a:bool)", "(?a ^ 1)"),
    ("xor-one-bool-to-not", "(?a:bool ^ 1)", "(!?a)"),
    ("eq-zero-to-not", "(?a == 0)", "(!?a)"),
    ("not-to-eq-zero", "(!?a:bool)", "(?a == 0)"),
    ("neq-zero-to-bool", "(?a != 0)", "?a:bool"),
    ("and-mask-all-ones", "(?a & (-1))", "?a"),
    ("or-with-zero", "(?a | 0)", "?a"),
    ("xor-self-cancel", "(?a ^ ?a)", "0"),
    ("shift-by-zero-left", "(?a << 0)", "?a"),
    ("shift-by-zero-right", "(?a >> 0)", "?a"),
    ("zero-shift-left", "(0 << ?a)", "0"),
    ("zero-shift-right", "(0 >> ?a)", "0"),
    (
        "mul-distribute-over-sub",
        "((?a - ?b) * ?c)",
        "((?a * ?c) - (?b * ?c))",
    ),
    (
        "mul-contract-over-sub",
        "((?a * ?c) - (?b * ?c))",
        "((?a - ?b) * ?c)",
    ),
    (
        "boolean-to-binary-mul",
        "(?cond:bool ? ?a : 0)",
        "(?cond * ?a)",
    ),
    (
        "binary-mul-to-boolean",
        "(?cond:bool * ?a)",
        "(?cond ? ?a : 0)",
    ),
    ("select-identity", "(?cond ? ?a : ?a)", "?a"),
    ("select-on-true", "(T ? ?a : ?b)", "?a"),
    ("select-on-false", "(F ? ?a : ?b)", "?b"),
    ("negate-select", "(?cond ? ?a : ?b)", "((!?cond) ? ?b : ?a)"),
    ("mod-by-one", "(?a % 1)", "0"),
    ("relation-eq-self", "(?a == ?a)", "T"),
    ("relation-neq-self", "(?a != ?a)", "F"),
    ("relation-lt-self", "(?a < ?a)", "F"),
    ("relation-gt-self", "(?a > ?a)", "F"),
    ("relation-leq-self", "(?a <= ?a)", "T"),
    ("relation-geq-self", "(?a >= ?a)", "T"),
    ("xor-associative", "((?a ^ ?b) ^ ?c)", "(?a ^ (?b ^ ?c))"),
    (
        "xor-associative-rev",
        "(?a ^ (?b ^ ?c))",
        "((?a ^ ?b) ^ ?c)",
    ),
    ("xor-commutative", "(?a ^ ?b)", "(?b ^ ?a)"),
];

pub const WEAKENING_RULES: &[(&str, &str, &str)] = &[
    (
        "assertion-weakening-with-equ-to-geq",
        "{assert (?a == ?b)}",
        "{assert (?a >= ?b)}",
    ),
    (
        "assertion-weakening-with-equ-to-leq",
        "{assert (?a == ?b)}",
        "{assert (?a <= ?b)}",
    ),
    (
        "assertion-weakening-with-gth-to-geq",
        "{assert (?a > ?b)}",
        "{assert (?a >= ?b)}",
    ),
    (
        "assertion-weakening-with-lth-to-leq",
        "{assert (?a < ?b)}",
        "{assert (?a <= ?b)}",
    ),
    (
        "assertion-weakening-with-gth-to-neq",
        "{assert (?a > ?b)}",
        "{assert (?a != ?b)}",
    ),
    (
        "assertion_weakening-with-lth-to-neq",
        "{assert (?a < ?b)}",
        "{assert (?a != ?b)}",
    ),
    (
        "assertion-weakening-with-equ-to-xor",
        "{assert (?a == ?b)}",
        "{assert ((?a ^ ?b) == 0)}",
    ),
    (
        "assertion-weakening-with-and-to-bor",
        "{assert (?a & ?b)}",
        "{assert (?a | ?b)}",
    ),
    (
        "assertion-weakening-drop-left-band",
        "{assert (?a & ?b)}",
        "{assert ?b}",
    ),
    (
        "assertion-weakening-drop-right-band",
        "{assert (?a & ?b)}",
        "{assert ?a}",
    ),
    (
        "assertion-weakening-neq-to-true",
        "{assert (?a != ?b)}",
        "{assert T}",
    ),
    (
        "assertion-weakening-geq-zero",
        "{assert (?a > ?b)}",
        "{assert (?a >= 0)}",
    ),
    (
        "assertion-weakening-leq-max",
        "{assert (?a < ?b)}",
        "{assert (?a <= ?b)}",
    ),
    (
        "assertion-weakening-add-or-left",
        "{assert ?a}",
        "{assert (?a | $r:bool)}",
    ),
    (
        "assertion-weakening-xor-to-neq",
        "{assert (?a ^ ?b)}",
        "{assert (?a != ?b)}",
    ),
    (
        "assertion-weakening-mul-nonzero",
        "{assert ((?a * ?b) != 0)}",
        "{assert (?a != 0)}",
    ),
    (
        "assertion-weakening-add-positive",
        "{assert ((?a + ?b) > ?c)}",
        "{assert (?a > ?c)}",
    ),
];
